-- RSS source expansion from the reviewed Feedspot, TeluguStop, DriveSpark,
-- and The Hindu publisher directories. Feedspot "Generate RSS" and homepage-only
-- entries are intentionally excluded.
--
-- Source priority among these additions:
--   1xxx Telugu general, 2xxx Telugu district, 3xxx Telugu automotive,
--   4xxx The Hindu sections, 5xxx remaining Indian publishers.
--
-- The NOT EXISTS comparison avoids trailing-slash variants of existing URLs while
-- ON CONFLICT preserves every existing feed_sources row unchanged.

with candidate_feeds (
  source,
  label,
  url,
  category_hint,
  active,
  display_order
) as (
values
  ('Telugu Mirchi', 'Telugu Mirchi', 'https://www.telugumirchi.com/telugu/feed', 'news', true, 1014),
  ('TeluguStop Local', 'TeluguStop - Kumarambheem Asifabad', 'https://telugustop.com/telugu/kumarambheem-asifabad-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2016),
  ('TeluguStop Local', 'TeluguStop - Mahabubabad', 'https://telugustop.com/telugu/mahabubabad-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2017),
  ('TeluguStop Local', 'TeluguStop - Mahabubnagar', 'https://telugustop.com/telugu/mahabubnagar-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2018),
  ('TeluguStop Local', 'TeluguStop - Mancherial', 'https://telugustop.com/telugu/mancherial-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2020),
  ('TeluguStop Local', 'TeluguStop - Medak', 'https://telugustop.com/telugu/medak-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2021),
  ('TeluguStop Local', 'TeluguStop - Medchal', 'https://telugustop.com/telugu/medchal-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2023),
  ('TeluguStop Local', 'TeluguStop - Malkajgiri', 'https://telugustop.com/telugu/malkajgiri-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2025),
  ('TeluguStop Local', 'TeluguStop - Nagarkurnool', 'https://telugustop.com/telugu/nagarkurnool-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2026),
  ('TeluguStop Local', 'TeluguStop - Nirmal', 'https://telugustop.com/telugu/nirmal-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2029),
  ('TeluguStop Local', 'TeluguStop - Nizamabad', 'https://telugustop.com/telugu/nizamabad-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2030),
  ('TeluguStop Local', 'TeluguStop - Peddapalli', 'https://telugustop.com/telugu/peddapalli-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2032),
  ('TeluguStop Local', 'TeluguStop - Sanga Reddy', 'https://telugustop.com/telugu/sanga-reddy-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2035),
  ('TeluguStop Local', 'TeluguStop - Siddipet', 'https://telugustop.com/telugu/siddipet-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2036),
  ('TeluguStop Local', 'TeluguStop - Vikarabad', 'https://telugustop.com/telugu/vikarabad-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2038),
  ('TeluguStop Local', 'TeluguStop - Wanaparthy', 'https://telugustop.com/telugu/wanaparthy-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2039),
  ('Andhrawatch', 'Andhrawatch', 'https://andhrawatch.com/feed/', 'news', true, 1000),
  ('NTV Telugu', 'NTV Telugu', 'https://ntvtelugu.com/feed', 'news', true, 1001),
  ('Visala Andhra', 'Visala Andhra', 'https://visalaandhra.com/feed/', 'news', true, 1002),
  ('OkTelugu', 'OkTelugu', 'https://oktelugu.com/feed', 'news', true, 1003),
  ('Telugu Bulletin', 'Telugu Bulletin', 'https://www.telugubulletin.com/feed', 'news', true, 1004),
  ('Telugu Stop', 'Telugu Stop', 'https://telugustop.com/feed', 'news', true, 1005),
  ('V6 Velugu', 'V6 Velugu', 'https://www.v6velugu.com/feed/', 'news', true, 1006),
  ('Telugu Rajyam', 'Telugu Rajyam', 'https://telugurajyam.com/feed', 'news', true, 1007),
  ('Adya News', 'Adya News', 'https://www.adya.news/telugu/feed/', 'news', true, 1008),
  ('Namasthe Telangana', 'Namasthe Telangana', 'https://www.ntnews.com/news/feed', 'news', true, 1009),
  ('Telugu360', 'Telugu360', 'https://www.telugu360.com/feed/', 'news', true, 1010),
  ('Telugu Journalist', 'Telugu Journalist', 'https://telugujournalist.com/category/news/feed/', 'news', true, 1011),
  ('Vaartha', 'Vaartha', 'https://vaartha.com/feed/', 'news', true, 1012),
  ('Prajatantra News', 'Prajatantra News', 'https://www.prajatantranews.com/feed/', 'news', true, 1015),
  ('TeluguISM', 'TeluguISM', 'https://teluguism.com/category/news/feed/', 'news', true, 1016),
  ('Telugu Post', 'Telugu Post', 'https://www.telugupost.com/latest-news/feed', 'news', true, 1017),
  ('10 TV', '10 TV', 'https://10tv.in/latest/feed', 'news', true, 1018),
  ('Manalokam', 'Manalokam', 'https://manalokam.com/news/feed', 'news', true, 1019),
  ('Telugu Bullet', 'Telugu Bullet', 'https://telugu.telugubullet.com/feed/', 'news', true, 1020),
  ('Disha Daily Local', 'Disha Daily - Khammam', 'https://www.dishadaily.com/category/telangana-khammam/feeds.xml', 'news', true, 2001),
  ('Disha Daily Local', 'Disha Daily - Adilabad', 'https://www.dishadaily.com/category/telangana-adilabad/feeds.xml', 'news', true, 2002),
  ('TeluguStop Local', 'TeluguStop - Bhadradri Kothagudem', 'https://telugustop.com/telugu/bhadradri-kothagudem-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2004),
  ('Disha Daily Local', 'Disha Daily - Rangareddy', 'https://www.dishadaily.com/category/telangana-rangareddy/feeds.xml', 'news', true, 2006),
  ('Disha Daily Local', 'Disha Daily - Hyderabad', 'https://www.dishadaily.com/category/telangana-hyderabad/feeds.xml', 'news', true, 2007),
  ('Disha Daily Local', 'Disha Daily - Karimnagar', 'https://www.dishadaily.com/category/telangana-karimnagar/feeds.xml', 'news', true, 2013),
  ('TeluguStop Local', 'TeluguStop - Kothagudem', 'https://telugustop.com/telugu/kothagudem-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2015),
  ('Disha Daily Local', 'Disha Daily - Mahabubnagar', 'https://www.dishadaily.com/category/telangana-mahabubnagar/feeds.xml', 'news', true, 2019),
  ('Disha Daily Local', 'Disha Daily - Medak', 'https://www.dishadaily.com/category/telangana-medak/feeds.xml', 'news', true, 2022),
  ('Disha Daily Local', 'Disha Daily - Medchal', 'https://www.dishadaily.com/category/telangana-medchal/feeds.xml', 'news', true, 2024),
  ('TeluguStop Local', 'TeluguStop - Nalgonda', 'https://telugustop.com/telugu/nalgonda-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2027),
  ('Disha Daily Local', 'Disha Daily - Nalgonda', 'https://www.dishadaily.com/category/telangana-nalgonda/feeds.xml', 'news', true, 2028),
  ('Disha Daily Local', 'Disha Daily - Nizamabad', 'https://www.dishadaily.com/category/telangana-nizamabad/feeds.xml', 'news', true, 2031),
  ('TeluguStop Local', 'TeluguStop - Rajanna Sircilla', 'https://telugustop.com/telugu/rajanna-sircilla-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2033),
  ('TeluguStop Local', 'TeluguStop - Suryapet', 'https://telugustop.com/telugu/suryapet-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2037),
  ('TeluguStop Local', 'TeluguStop - Warangal', 'https://telugustop.com/telugu/warangal-district-city-latest-update-news/feed?news_feed=tstop_app', 'news', true, 2040),
  ('Disha Daily Local', 'Disha Daily - Warangal', 'https://www.dishadaily.com/category/telangana-warangal/feeds.xml', 'news', true, 2041),
  ('TeluguStop Local', 'TeluguStop - Yadadri Bhuvanagiri', 'https://telugustop.com/telugu/yadadri-bhuvanagiri-district-city-daily-latest-news/feed?news_feed=tstop_app', 'news', true, 2042),
  ('Disha Daily Local', 'Disha Daily - Anantapuram', 'https://www.dishadaily.com/category/andhrapradesh-anantapuram/feeds.xml', 'news', true, 2044),
  ('Disha Daily Local', 'Disha Daily - Chittoor', 'https://www.dishadaily.com/category/andhrapradesh-chittoor/feeds.xml', 'news', true, 2046),
  ('Disha Daily Local', 'Disha Daily - West Godavari', 'https://www.dishadaily.com/category/andhrapradesh-west-godavari/feeds.xml', 'news', true, 2048),
  ('Disha Daily Local', 'Disha Daily - Guntur', 'https://www.dishadaily.com/category/andhrapradesh-guntur/feeds.xml', 'news', true, 2051),
  ('Disha Daily Local', 'Disha Daily - Ysr', 'https://www.dishadaily.com/category/andhrapradesh-ysr-district/feeds.xml', 'news', true, 2053),
  ('Disha Daily Local', 'Disha Daily - Krishna', 'https://www.dishadaily.com/category/andhrapradesh-krishna/feeds.xml', 'news', true, 2055),
  ('Disha Daily Local', 'Disha Daily - Kurnool', 'https://www.dishadaily.com/category/andhrapradesh-kurnool/feeds.xml', 'news', true, 2058),
  ('Disha Daily Local', 'Disha Daily - Sri Potti Sriramulu Nellore', 'https://www.dishadaily.com/category/andhrapradesh-sri-potti-sriramulu-nellore-district/feeds.xml', 'news', true, 2060),
  ('Disha Daily Local', 'Disha Daily - Prakasam', 'https://www.dishadaily.com/category/andhrapradesh-prakasam/feeds.xml', 'news', true, 2062),
  ('Disha Daily Local', 'Disha Daily - Srikakulam', 'https://www.dishadaily.com/category/andhrapradesh-srikakulam/feeds.xml', 'news', true, 2065),
  ('Disha Daily Local', 'Disha Daily - Visakhapatnam', 'https://www.dishadaily.com/category/andhrapradesh-visakhapatnam/feeds.xml', 'news', true, 2067),
  ('Disha Daily Local', 'Disha Daily - Vizianagaram', 'https://www.dishadaily.com/category/andhrapradesh-vizianagaram/feeds.xml', 'news', true, 2069),
  ('Disha Daily Local', 'Disha Daily - East Godavari', 'https://www.dishadaily.com/category/andhrapradesh-east-godavari/feeds.xml', 'news', true, 2071),
  ('NDTV', 'NDTV - Bangalore', 'https://feeds.feedburner.com/NDTV-LatestNews', 'news', true, 2072),
  ('The Hindu', 'The Hindu - News', 'https://www.thehindu.com/news/feeder/default.rss', 'news', true, 4000),
  ('The Hindu', 'The Hindu - News - National', 'https://www.thehindu.com/news/national/feeder/default.rss', 'news', true, 4001),
  ('The Hindu', 'The Hindu - News - International', 'https://www.thehindu.com/news/international/feeder/default.rss', 'news', true, 4002),
  ('The Hindu', 'The Hindu - News - States', 'https://www.thehindu.com/news/states/feeder/default.rss', 'news', true, 4003),
  ('The Hindu', 'The Hindu - News - Cities', 'https://www.thehindu.com/news/cities/feeder/default.rss', 'news', true, 4004),
  ('The Hindu', 'The Hindu - Opinion', 'https://www.thehindu.com/opinion/feeder/default.rss', 'news', true, 4005),
  ('The Hindu', 'The Hindu - Opinion - Cartoon', 'https://www.thehindu.com/opinion/cartoon/feeder/default.rss', 'news', true, 4006),
  ('The Hindu', 'The Hindu - Opinion - Columns', 'https://www.thehindu.com/opinion/columns/feeder/default.rss', 'news', true, 4007),
  ('The Hindu', 'The Hindu - Opinion - Op Ed', 'https://www.thehindu.com/opinion/op-ed/feeder/default.rss', 'news', true, 4008),
  ('The Hindu', 'The Hindu - Opinion - Editorial', 'https://www.thehindu.com/opinion/editorial/feeder/default.rss', 'news', true, 4009),
  ('The Hindu', 'The Hindu - Opinion - Interview', 'https://www.thehindu.com/opinion/interview/feeder/default.rss', 'news', true, 4010),
  ('The Hindu', 'The Hindu - Opinion - Lead', 'https://www.thehindu.com/opinion/lead/feeder/default.rss', 'news', true, 4011),
  ('The Hindu', 'The Hindu - Opinion - Letters', 'https://www.thehindu.com/opinion/letters/feeder/default.rss', 'news', true, 4012),
  ('The Hindu', 'The Hindu - Opinion - Open Page', 'https://www.thehindu.com/opinion/open-page/feeder/default.rss', 'news', true, 4013),
  ('The Hindu', 'The Hindu - Opinion - Readers Editor', 'https://www.thehindu.com/opinion/Readers-Editor/feeder/default.rss', 'news', true, 4014),
  ('The Hindu', 'The Hindu - Opinion - Readers Editor - Corrections And Clarifications', 'https://www.thehindu.com/opinion/Readers-Editor/corrections-and-clarifications/feeder/default.rss', 'news', true, 4015),
  ('The Hindu', 'The Hindu - Business', 'https://www.thehindu.com/business/feeder/default.rss', 'business', true, 4016),
  ('The Hindu', 'The Hindu - Business - Agri Business', 'https://www.thehindu.com/business/agri-business/feeder/default.rss', 'business', true, 4017),
  ('The Hindu', 'The Hindu - Business - Industry', 'https://www.thehindu.com/business/Industry/feeder/default.rss', 'business', true, 4018),
  ('The Hindu', 'The Hindu - Business - Economy', 'https://www.thehindu.com/business/Economy/feeder/default.rss', 'business', true, 4019),
  ('The Hindu', 'The Hindu - Business - Markets', 'https://www.thehindu.com/business/markets/feeder/default.rss', 'business', true, 4020),
  ('The Hindu', 'The Hindu - Business - Budget', 'https://www.thehindu.com/business/budget/feeder/default.rss', 'business', true, 4021),
  ('The Hindu', 'The Hindu - Sport', 'https://www.thehindu.com/sport/feeder/default.rss', 'sports', true, 4022),
  ('The Hindu', 'The Hindu - Sport - Cricket', 'https://www.thehindu.com/sport/cricket/feeder/default.rss', 'sports', true, 4023),
  ('The Hindu', 'The Hindu - Sport - Football', 'https://www.thehindu.com/sport/football/feeder/default.rss', 'sports', true, 4024),
  ('The Hindu', 'The Hindu - Sport - Hockey', 'https://www.thehindu.com/sport/hockey/feeder/default.rss', 'sports', true, 4025),
  ('The Hindu', 'The Hindu - Sport - Tennis', 'https://www.thehindu.com/sport/tennis/feeder/default.rss', 'sports', true, 4026),
  ('The Hindu', 'The Hindu - Sport - Athletics', 'https://www.thehindu.com/sport/athletics/feeder/default.rss', 'sports', true, 4027),
  ('The Hindu', 'The Hindu - Sport - Motorsport', 'https://www.thehindu.com/sport/motorsport/feeder/default.rss', 'sports', true, 4028),
  ('The Hindu', 'The Hindu - Sport - Races', 'https://www.thehindu.com/sport/races/feeder/default.rss', 'sports', true, 4029),
  ('The Hindu', 'The Hindu - Sport - Other Sports', 'https://www.thehindu.com/sport/other-sports/feeder/default.rss', 'sports', true, 4030),
  ('The Hindu', 'The Hindu - Entertainment', 'https://www.thehindu.com/entertainment/feeder/default.rss', 'movies', true, 4031),
  ('The Hindu', 'The Hindu - Entertainment - Art', 'https://www.thehindu.com/entertainment/art/feeder/default.rss', 'movies', true, 4032),
  ('The Hindu', 'The Hindu - Entertainment - Dance', 'https://www.thehindu.com/entertainment/dance/feeder/default.rss', 'movies', true, 4033),
  ('The Hindu', 'The Hindu - Entertainment - Movies', 'https://www.thehindu.com/entertainment/movies/feeder/default.rss', 'movies', true, 4034),
  ('The Hindu', 'The Hindu - Entertainment - Music', 'https://www.thehindu.com/entertainment/music/feeder/default.rss', 'movies', true, 4035),
  ('The Hindu', 'The Hindu - Entertainment - Reviews', 'https://www.thehindu.com/entertainment/reviews/feeder/default.rss', 'movies', true, 4036),
  ('The Hindu', 'The Hindu - Entertainment - Theatre', 'https://www.thehindu.com/entertainment/theatre/feeder/default.rss', 'movies', true, 4037),
  ('The Hindu', 'The Hindu - Sci Tech - Science', 'https://www.thehindu.com/sci-tech/science/feeder/default.rss', 'tech', true, 4038),
  ('The Hindu', 'The Hindu - Life And Style', 'https://www.thehindu.com/life-and-style/feeder/default.rss', 'health', true, 4039),
  ('The Hindu', 'The Hindu - Life And Style - Fashion', 'https://www.thehindu.com/life-and-style/fashion/feeder/default.rss', 'health', true, 4040),
  ('The Hindu', 'The Hindu - Life And Style - Fitness', 'https://www.thehindu.com/life-and-style/fitness/feeder/default.rss', 'health', true, 4041),
  ('The Hindu', 'The Hindu - Life And Style - Food', 'https://www.thehindu.com/life-and-style/food/feeder/default.rss', 'health', true, 4042),
  ('The Hindu', 'The Hindu - Life And Style - Motoring', 'https://www.thehindu.com/life-and-style/motoring/feeder/default.rss', 'health', true, 4043),
  ('The Hindu', 'The Hindu - Life And Style - Travel', 'https://www.thehindu.com/life-and-style/travel/feeder/default.rss', 'health', true, 4044),
  ('The Hindu', 'The Hindu - Life And Style - Homes And Gardens', 'https://www.thehindu.com/life-and-style/homes-and-gardens/feeder/default.rss', 'health', true, 4045),
  ('The Hindu', 'The Hindu - Life And Style - Luxury', 'https://www.thehindu.com/life-and-style/luxury/feeder/default.rss', 'health', true, 4046),
  ('The Hindu', 'The Hindu', 'https://www.thehindu.com/news/national/?service=rss', 'news', true, 5000),
  ('Indian Express', 'Indian Express', 'https://indianexpress.com/feed/', 'news', true, 5001),
  ('Hindustan Times', 'Hindustan Times', 'https://www.hindustantimes.com/feeds/rss/latest/rssfeed.xml', 'news', true, 5003),
  ('The Times of India', 'The Times of India', 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms', 'news', true, 5004),
  ('India Today » India', 'India Today » India', 'https://www.indiatoday.in/rss/1206578', 'news', true, 5005),
  ('Scroll.in', 'Scroll.in', 'https://feeds.feedburner.com/ScrollinArticles.rss', 'news', true, 5006),
  ('Frontline', 'Frontline', 'https://frontline.thehindu.com/cover-story/feeder/default.rss', 'news', true, 5007),
  ('Business Standard', 'Business Standard » Latest News', 'https://www.business-standard.com/rss/latest.rss', 'business', true, 5008),
  ('The Hindu Business Line', 'The Hindu Business Line', 'https://www.thehindubusinessline.com/?service=rss', 'news', true, 5009),
  ('News18', 'News18', 'https://www.news18.com/commonfeeds/v1/eng/rss/text.xml', 'news', true, 5010),
  ('Times Now', 'Times Now', 'https://www.timesnownews.com/feeds/gns-en-latest.xml', 'news', true, 5011),
  ('ABP News', 'ABP News', 'https://news.abplive.com/home/feed', 'news', true, 5012),
  ('India TV News » Top Stories', 'India TV News » Top Stories', 'https://www.indiatvnews.com/rssnews/topstory.xml', 'news', true, 5013),
  ('Free Press Journal', 'Free Press Journal', 'https://prod-qt-images.s3.amazonaws.com/production/freepressjournal/feed.xml', 'news', true, 5014),
  ('Amar Ujala', 'Amar Ujala', 'https://www.amarujala.com/rss/breaking-news.xml', 'news', true, 5016),
  ('Telangana Today', 'Telangana Today', 'https://telanganatoday.com/feed', 'news', true, 5017),
  ('The Quint', 'The Quint', 'https://prod-qt-images.s3.amazonaws.com/production/thequint/feed.xml', 'news', true, 5018),
  ('Firstpost', 'Firstpost', 'https://www.firstpost.com/commonfeeds/v1/mfp/rss/web-stories.xml', 'news', true, 5019),
  ('Alt News', 'Alt News', 'https://www.altnews.in/feed/', 'news', true, 5020),
  ('The Assam Tribune', 'The Assam Tribune', 'https://assamtribune.com/feed', 'news', true, 5021),
  ('The Arunachal Times', 'The Arunachal Times', 'https://arunachaltimes.in/index.php/feed/', 'news', true, 5022),
  ('The News Mill', 'The News Mill', 'https://thenewsmill.com/feed/', 'news', true, 5025),
  ('Greater Kashmir', 'Greater Kashmir', 'https://prod-qt-images.s3.amazonaws.com/production/greaterkashmir/feed.xml', 'news', true, 5027),
  ('Rising Kashmir', 'Rising Kashmir', 'https://risingkashmir.com/feed/', 'news', true, 5028),
  ('Kashmir Observer', 'Kashmir Observer', 'https://kashmirobserver.net/feed/', 'news', true, 5029),
  ('Kashmir Reader', 'Kashmir Reader', 'https://feeds.feedburner.com/kashmir-reader', 'news', true, 5030),
  ('JK Newsline', 'JK Newsline', 'https://jknewsline.com/feed/', 'news', true, 5032),
  ('Kashmir News', 'Kashmir News', 'https://kashmirnews.in/feed/', 'news', true, 5033),
  ('Star Of Mysore', 'Star Of Mysore', 'https://starofmysore.com/feed/', 'news', true, 5035),
  ('Chandigarh Metro', 'Chandigarh Metro', 'https://chandigarhmetro.com/feed/', 'news', true, 5036),
  ('Chandigarh City News', 'Chandigarh City News', 'https://feeds.feedburner.com/ChandigarhCityNews', 'news', true, 5037),
  ('Bangalore Today', 'Bangalore Today', 'https://bangaloretoday.in/feed/', 'news', true, 5038),
  ('The Live Nagpur', 'The Live Nagpur', 'https://thelivenagpur.com/feed/', 'news', true, 5039),
  ('OrissaPOST', 'OrissaPOST', 'https://www.orissapost.com/feed/', 'news', true, 5040),
  ('Odishabarta', 'Odishabarta', 'https://odishabarta.com/feed/', 'news', true, 5041),
  ('Assam Times', 'Assam Times', 'https://www.assamtimes.org/rss.xml', 'news', true, 5042),
  ('India.com', 'India.com', 'https://www.india.com/feed/', 'news', true, 5043),
  ('DNA', 'DNA', 'https://www.dnaindia.com/feeds/india.xml', 'news', true, 5044),
  ('National Herald', 'National Herald', 'https://prod-qt-images.s3.amazonaws.com/production/nationalherald/feed.xml', 'news', true, 5045),
  ('Organiser Weekly', 'Organiser Weekly', 'https://organiser.org/feed/', 'news', true, 5046),
  ('OpIndia', 'OpIndia', 'https://www.opindia.com/feed/', 'news', true, 5047),
  ('TFIPOST', 'TFIPOST', 'https://tfipost.com/feed/', 'news', true, 5048),
  ('Social Samosa', 'Social Samosa', 'http://feeds.feedburner.com/SocialSamosa', 'tech', true, 5049),
  ('TechGenYZ', 'TechGenYZ', 'https://techgenyz.com/feed/', 'tech', true, 5050),
  ('Startup Reporter', 'Startup Reporter', 'https://startupreporter.in/feed/', 'business', true, 5051),
  ('BioVoice News', 'BioVoice News', 'https://biovoicenews.com/feed/', 'health', true, 5052),
  ('KNN India', 'KNN India', 'https://knnindia.co.in/newsfeed/feedbycategory', 'business', true, 5053),
  ('News1India', 'News1India', 'https://news1india.in/feed/', 'news', true, 5054),
  ('IndiaVision', 'IndiaVision', 'https://www.indiavision.com/feed/', 'news', true, 5055),
  ('APN Live', 'APN Live', 'https://apnlive.com/feed/', 'news', true, 5056),
  ('Delhi Post News', 'Delhi Post News', 'https://delhipostnews.com/feed/', 'news', true, 5057),
  ('The News Himachal', 'The News Himachal', 'https://thenewshimachal.com/feed/', 'news', true, 5058),
  ('Bilkul Online', 'Bilkul Online', 'http://bilkulonline.com/feed/', 'news', true, 5059),
  ('Sangri Today', 'Sangri Today', 'https://www.sangritoday.com/rss/latest-posts', 'news', true, 5060),
  ('Newsblare', 'Newsblare', 'https://newsblare.com/feed/', 'news', true, 5061),
  ('India Observers', 'India Observers', 'https://indiaobservers.com/feed/', 'news', true, 5062),
  ('Informal Newz', 'Informal Newz', 'https://www.informalnewz.com/feed/', 'business', true, 5063),
  ('The India Bizz', 'The India Bizz', 'https://theindiabizz.com/feed/', 'business', true, 5064),
  ('India''s News.Net', 'India''s News.Net', 'http://feeds.indiasnews.net/rss/701ee96610c884a6', 'news', true, 5065)
)
insert into public.feed_sources (
  source,
  label,
  url,
  category_hint,
  active,
  display_order
)
select
  candidate.source,
  candidate.label,
  candidate.url,
  candidate.category_hint,
  candidate.active,
  candidate.display_order
from candidate_feeds as candidate
where not exists (
  select 1
  from public.feed_sources as existing
  where lower(rtrim(existing.url, '/')) = lower(rtrim(candidate.url, '/'))
)
on conflict (url) do nothing;
